baseURL = 'https://husnulhamidiah.github.io'
languageCode = 'en-us'
title = 'ho͝osnul'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A personal blog curated by Husnul Anwari."

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm an Indonesian software engineer who enjoys tinkering with ideas and turning them into code. I'm always exploring new ways to build, experiment with, and improve systems.

Beyond programming, I enjoy writing, photography, and art — even if I'm not particularly good at it.

Feel free to read more [about me](/about) or browse my [posts](/posts).
"""

singleDateFormat = '2 Jan 2006'

# Collection to display on home
# homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = false
listDateFormat = '02 Jan 2006'

# Footer
showFooter = false

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/husnul-anwari/"

[[params.social]]
name = "github"
url = "https://github.com/husnulhamidiah"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/analogsaurus/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
noClasses = false

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[params.umami]
enable = false
jsLocation = "https://cloud.umami.is/script.js"
websiteId = "your website id"